//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookOcean.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookSet
    {
        public long SetId { get; set; }
        public int ClassID { get; set; }
        public string SetName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> BookId { get; set; }
    
        public virtual Standard Standard { get; set; }
    }
}
