//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookOcean.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public long Id { get; set; }
        public Nullable<long> SetID { get; set; }
        public Nullable<long> BookID { get; set; }
    }
}
